seed: 67

data:
  root: "./data"
  batch_size: 128
  train_size: 50000
  validation_size: 10000

model:
  latent_dim: 8

training:
  epochs: 25
  learning_rate: 1e-5
  beta_one: 0.99
  beta_two: 0.9
  weight_decay: 1e-6

loss:
  beta: 1

scheduler:
  step_size: 10
  gamma: 0.9